### ISSUE TITLE
Things this need to show

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Krypton-Toolkit-Suite-Version-Dashboard#1]
Build types
- Alpha (Nightly)
- Canary
- Latest release
- previous LTS style release

Changelogs for each
- gitHub is able to perform a comparison of checkins against different branches, and then display it as a timeline table
- Make sure checkin titles and comments explain what has changes (i.e. "fixes " is not good enough!)

Links to the Example images / installers

Nuget packages to point this location

**Comment by PWagner1** [comment]
Completed 10/01/2022
